services:
  # Backend API Service
  - type: web
    name: relevia-backend
    runtime: python
    buildCommand: "cd backend && pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    pythonVersion: 3.11.9
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: relevia-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production

databases:
  - name: relevia-db
    plan: free
    databaseName: relevia
    user: relevia