version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: relevia-postgres
    environment:
      POSTGRES_USER: releviauser
      POSTGRES_PASSWORD: releviapass123
      POSTGRES_DB: relevia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: